# Generated by Django 2.2.7 on 2019-11-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, choices=[('DAISY', 'daisy'), ('DANDELION', 'dandelion'), ('ROSE', 'rose'), ('SUNFLOWER', 'sunflower'), ('TULIP', 'tulip')], max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
